//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKS_Thuc_Tap_Web.WebAdmin.Admin {
    
    
    public partial class Doi_Mat_Khau {
        
        /// <summary>
        /// uc1008_Doi_Mat_Khau1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TKS_Thuc_Tap_Web.WebAdmin.Admin.UserControl.uc1008_Doi_Mat_Khau uc1008_Doi_Mat_Khau1;
    }
}
